### PR TITLE
make version parameter optional in kitchen yml

### PR DESCRIPTION
**Pull request by kasif-adnan**
Signed-off-by: kasif <kadnan@progress.com>

### Description

This PR makes providing version attribute optional in the kitchen yml template

### Check List

- [x] All tests pass.
- [x] All style checks pass.
- [x] Functionality includes testing.
- [ ] Functionality has been documented in the README if applicable

### CODE REVIEW

**Review by sanjain-progress — APPROVED** [review]

**Comment by larry-herz** [comment]
Should the readme be updated as well to reflect the now optional nature of the version attribute?

**Comment by tas50** [comment]
We need to make sure any docs update happen in https://github.com/test-kitchen/test-kitchen/blob/main/docs/content/docs/drivers/vra.md

**Comment by tas50** [comment]
Since this requires the new functionality in the 3.1.0 gem we need to make sure to dep on >= 3.1.0

**Comment by kasif-adnan** [comment]
@tas50 , updated the docs here https://github.com/test-kitchen/test-kitchen/pull/1857

**Pull request merged**
